os: osx
language: objective-c
osx_image: xcode10.1
sudo: false
env:
  global:
  - THEOS=~/theos
before_install:
- brew install dpkg ldid
- git clone --recursive git://github.com/theos/theos.git ~/theos
script:
- make clean package
before_deploy:
- git config --local user.name "Squ1dd13"
- git config --local user.email "squ1dd13dev@gmail.com"
- export RELEASE_PKG_FILE=$(ls ./packages/*.deb)
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
